### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by Sadegh-Kalami** [GetOverMassif/pyORBSLAM3#2]
Hi,
I am interested and enthusiastic about collaborating to further develop your repository and code, as this field deeply interests me. You can review my work and background on my homepage at [sadegh-kalami.github.io](https://sadegh-kalami.github.io/).

I’m looking forward to the opportunity to contribute to an open-source repository that could benefit others. This could be a promising beginning for our mutual endeavors.

Best regards,
Kalami

**Comment by GetOverMassif** [comment]
That's great, what kind of collaboration do you like?

**Comment by GetOverMassif** [comment]
> Hi, I am interested and enthusiastic about collaborating to further develop your repository and code, as this field deeply interests me. You can review my work and background on my homepage at [sadegh-kalami.github.io](https://sadegh-kalami.github.io/).
> 
> I’m looking forward to the opportunity to contribute to an open-source repository that could benefit others. This could be a promising beginning for our mutual endeavors.
> 
> Best regards, Kalami


That's great, what kind of collaboration do you like?
